# CMake generated Testfile for 
# Source directory: /home/dev/projects/cppGame
# Build directory: /home/dev/projects/cppGame/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[engine_math_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[math]")
set_tests_properties([=[engine_math_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;225;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_camera_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[camera]")
set_tests_properties([=[engine_camera_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;226;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_zone_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[zone]")
set_tests_properties([=[engine_zone_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;227;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_loot_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[loot]")
set_tests_properties([=[engine_loot_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;228;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_inventory_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[inventory]")
set_tests_properties([=[engine_inventory_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;229;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_trade_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[trade]")
set_tests_properties([=[engine_trade_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;230;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_minimap_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[minimap]")
set_tests_properties([=[engine_minimap_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;231;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_ui_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[ui]")
set_tests_properties([=[engine_ui_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;232;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_combat_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[combat]")
set_tests_properties([=[engine_combat_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;233;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_souls_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[souls]")
set_tests_properties([=[engine_souls_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;234;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_items_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[items]")
set_tests_properties([=[engine_items_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;235;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_replayability_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[replayability]")
set_tests_properties([=[engine_replayability_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;236;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_save_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[save]")
set_tests_properties([=[engine_save_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;237;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_mastery_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[mastery]")
set_tests_properties([=[engine_mastery_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;238;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_mobs_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[mobs]")
set_tests_properties([=[engine_mobs_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;239;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_world_props_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[world]")
set_tests_properties([=[engine_world_props_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;240;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_boot_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[boot]")
set_tests_properties([=[engine_boot_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;264;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_playthrough_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[playthrough]")
set_tests_properties([=[engine_playthrough_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;265;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
add_test([=[engine_performance_suite]=] "/home/dev/projects/cppGame/build-release/EngineTests" "[performance]")
set_tests_properties([=[engine_performance_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/dev/projects/cppGame/CMakeLists.txt;266;add_test;/home/dev/projects/cppGame/CMakeLists.txt;0;")
subdirs("_deps/catch2-build")
