if(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
    include(EmscriptenDeps)
elseif(ENGINE_WINDOWS_CROSS OR (WIN32 AND NOT ENGINE_FORCE_LINUX_DEPS))
    include(WindowsCrossDeps)
else()
    include(LinuxNativeDeps)
endif()

function(engine_link_glm target_name)
    if(TARGET glm::glm)
        target_link_libraries(${target_name} PUBLIC glm::glm)
    elseif(TARGET PkgConfig::GLM)
        target_link_libraries(${target_name} PUBLIC PkgConfig::GLM)
    endif()
endfunction()
